# constant
span: 0.02

# tracker param
black: 0
nonblack: 1

# variable
# cmd_vel
dir: 0

V: 5.0
dV: 0.0
w: 0.0

# realspeed
rVx: 0.0
rVy: 0.0
rw: 0.0

# transmission fix

vkp: 1
vki: 0.0
vkd: 0.03

# rotation fix

wkp: 0.05
wki: 0.0
wkd: 0.003