# constant
span: 0.02

# tracker param
black: 0
nonblack: 1

# variable
# cmd_vel
ori: 0

V: 10.0
vel_limit: 3.0

# transmission fix

vkp: 1
vki: 0.0
vkd: 0.0

# rotation fix

wkp: 0.05
wki: 0.0
wkd: 0.00